name: EfficiencyCockpit
options:
  bundleIdPrefix: com.efficiency
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    ENABLE_HARDENED_RUNTIME: YES

targets:
  EfficiencyCockpit:
    type: application
    platform: macOS
    sources:
      - path: EfficiencyCockpit
        excludes:
          - "**/*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.efficiency.cockpit
        INFOPLIST_FILE: EfficiencyCockpit/Info.plist
        CODE_SIGN_ENTITLEMENTS: EfficiencyCockpit/EfficiencyCockpit.entitlements
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_NAME: "Efficiency Cockpit"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        # Menu bar app - no dock icon
        INFOPLIST_KEY_LSUIElement: YES
    entitlements:
      path: EfficiencyCockpit/EfficiencyCockpit.entitlements
    info:
      path: EfficiencyCockpit/Info.plist

  EfficiencyCockpitMCPServer:
    type: tool
    platform: macOS
    sources:
      - path: EfficiencyCockpitMCPServer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.efficiency.cockpit.mcpserver
        PRODUCT_NAME: EfficiencyCockpitMCPServer
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"

schemes:
  EfficiencyCockpit:
    build:
      targets:
        EfficiencyCockpit: all
        EfficiencyCockpitMCPServer: all
    run:
      config: Debug
      executable: EfficiencyCockpit
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
